### ISSUE TITLE
Error: java.lang.NoSuchMethodError: scala.Predef$.ArrowAssoc

### ISSUE THREAD

**Issue by samikrc** [subprotocol/spark-avro-example#2]
Hi,
When running a job using spark-submit, I am running into the following issue:

16/12/24 11:57:18 INFO mapreduce.AvroKeyInputFormat: Using a reader schema equal to the writer schema.
16/12/24 11:57:18 INFO output.FileOutputCommitter: File Output Committer Algorithm version is 1
16/12/24 11:57:18 ERROR executor.Executor: Exception in task 0.0 in stage 0.0 (TID 0)
java.lang.NoSuchMethodError: scala.Predef$.ArrowAssoc(Ljava/lang/Object;)Ljava/lang/Object;
	at com.ilabs.dsi.datapipes.AvroUtil$$anonfun$1$$anonfun$apply$1.apply(AvroUtil.scala:84)
	at com.ilabs.dsi.datapipes.AvroUtil$$anonfun$1$$anonfun$apply$1.apply(AvroUtil.scala:84)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsNewAPIHadoopDataset$1$$anonfun$12$$anonfun$apply$4.apply$mcV$sp(PairRDDFunctions.scala:1112)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsNewAPIHadoopDataset$1$$anonfun$12$$anonfun$apply$4.apply(PairRDDFunctions.scala:1111)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsNewAPIHadoopDataset$1$$anonfun$12$$anonfun$apply$4.apply(PairRDDFunctions.scala:1111)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1250)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsNewAPIHadoopDataset$1$$anonfun$12.apply(PairRDDFunctions.scala:1119)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsNewAPIHadoopDataset$1$$anonfun$12.apply(PairRDDFunctions.scala:1091)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
	at org.apache.spark.scheduler.Task.run(Task.scala:89)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:213)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
16/12/24 11:57:18 ERROR util.SparkUncaughtExceptionHandler: Uncaught exception in thread Thread[Executor task launch worker-0,5,main]
java.lang.NoSuchMethodError: scala.Predef$.ArrowAssoc(Ljava/lang/Object;)Ljava/lang/Object;
	at com.ilabs.dsi.datapipes.AvroUtil$$anonfun$1$$anonfun$apply$1.apply(AvroUtil.scala:84)
	at com.ilabs.dsi.datapipes.AvroUtil$$anonfun$1$$anonfun$apply$1.apply(AvroUtil.scala:84)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsNewAPIHadoopDataset$1$$anonfun$12$$anonfun$apply$4.apply$mcV$sp(PairRDDFunctions.scala:1112)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsNewAPIHadoopDataset$1$$anonfun$12$$anonfun$apply$4.apply(PairRDDFunctions.scala:1111)
....
....

I have copied the files "AvroUtil.scala" and "DirectFileOutputCommitter.scala" in my project, compiling it and using the AvroUtil.write method. I am running the whole setup on my VM, where I have installed hadoop 2.7.1. and spark 1.6.0 (the versions are intentionally downgraded in order to match our HDP cluster setup).

I searched the web for this error and the typical response is that this happens because of scala version mismatch. I am running the whole thing with scala 2.11.8 installed on my VM, and the project pom.xml has spark-core_2.11 as the dependency.

I tried downgrading the spark-core to spark-core_2.10 in pom, but that did not help.

Do you have any pointers about how to resolve this issue? The issue seems to stem from the following part of the code:

        // convert RDD into serializable format
        val intermediateRdd = avroRdd.mapPartitions(
            f = (iter: Iterator[T]) => iter.map(new AvroKey(_) -> NullWritable.get())
            , preservesPartitioning = true
        )

Regards.
-Samik

**Comment by vibnimit** [comment]
Hey Samik,
I am doing something similar and I am also stuck on the same thing and all the web is suggesting is the scala version conflict.

My Error:
 User class threw exception: java.lang.NoSuchMethodError: scala.Predef$.ArrowAssoc(Ljava/lang/Object;)Ljava/lang/Object;
java.lang.NoSuchMethodError: scala.Predef$.ArrowAssoc(Ljava/lang/Object;)Ljava/lang/Object;
       at org.apache.spark.sql.SparkSession$Builder.config(SparkSession.scala:800)
       at org.apache.spark.sql.SparkSession$Builder.appName(SparkSession.scala:791)
       at com.paypal.teammatesdataprocess.InitSpark$class.$init$(InitSpark.scala:8)
       at com.paypal.teammatesdataprocess.CustomerJourneyFPTIConsumer$.<init>(CustomerJourneyFPTIConsumer.scala:24)
       at com.paypal.teammatesdataprocess.CustomerJourneyFPTIConsumer$.<clinit>(CustomerJourneyFPTIConsumer.scala)
       at com.paypal.teammatesdataprocess.CustomerJourneyFPTIConsumer.main(CustomerJourneyFPTIConsumer.scala)
       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
       at java.lang.reflect.Method.invoke(Method.java:498)
       at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$2.run(ApplicationMaster.scala:561)
19/08/01 16:13:54 INFO ApplicationMaster: Final app status: FAILED, exitCode: 15, (reason: User class threw exception: java.lang.NoSuchMethodError: scala.Predef$.ArrowAssoc(Ljava/lang/Object;)Ljava/lang/Object;)
19/08/01 16:14:04 ERROR ApplicationMaster: SparkContext did not initialize after waiting for 100000 ms. Please check earlier log output for errors. Failing the application.
19/08/01 16:14:04 INFO ApplicationMaster: Unregistering ApplicationMaster with FAILED (diag message: User class threw exception: java.lang.NoSuchMethodError: scala.Predef$.ArrowAssoc(Ljava/lang/Object;)Ljava/lang/Object;)
19/08/01 16:14:04 INFO ApplicationMaster: Deleting staging directory .sparkStaging/application_1563828056991_283816
19/08/01 16:14:04 INFO ShutdownHookManager: Shutdown hook called

**Comment by samikrc** [comment]
Are you using the same code described in the OP? Anyways, can't exactly remember what I did back then, it probably was because Spark was loading some different library (version) than what I was expecting.

**Comment by samikrc** [comment]
Closing this - too old.
